
services:
  reservalab-backend-postgres:
    image: postgres:17.3
    container_name: reservalab-postgres-stage
    hostname: postgres
    restart: unless-stopped
    volumes:
      - reservalab-database:/var/lib/postgresql/data
    ports:
      - '127.0.0.1:5440:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_reservalab_production_98
      POSTGRES_DB: reservalab-stage
    networks:
      - reservalab-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}", "-d", "reservalab-stage"]
      interval: 5s
      timeout: 120s
      retries: 30
      start_period: 10s
  
  reservalab-backend:
    build:
      context: ./
      dockerfile: Dockerfile.production
    image: reservalab-backend:stage
    container_name: reservalab-backend-stage
    hostname: backend
    restart: unless-stopped
    ports:
      - '8080:8080'
    volumes:
      - ./src:/src
      - ./prisma:/src/prisma
      - ./package.json:/src/package.json
    depends_on:
      reservalab-backend-postgres:
        condition: service_healthy
    networks:
      - reservalab-network

volumes:
  reservalab-database:

networks:
  reservalab-network:
    name: reservalab-network
    driver: bridge
