version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ReservaLab
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ReservaLab-backend-dev
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://user:password@db:5432/ReservaLab
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npx prisma generate && npx prisma migrate dev --name init && npm run start:dev"

volumes:
  pgdata:
