# ⚠️ Este compose é para rodar o backend isoladamente em ambiente local.
# Para rodar toda a aplicação, use o docker-compose do repositório orquestrador.

version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ReservaLabPostgreSQL
      POSTGRES_DB: ReservaLab
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: .
    container_name: reserva-backend-local
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:ReservaLabPostgreSQL@db:5432/ReservaLab
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npx prisma generate && npx prisma migrate dev --name init && npm run start:dev"

volumes:
  pgdata:
