version: "3.9"

services:
#############
## backend ##
#############

  reservalab-backend-postgres:
    build:
      context: ./Database
      dockerfile: Dockerfile.production
    image: mattrodriguesec/reservalab-postgres:stage
    pull_policy: build

  reservalab-backend:
    build:
      context: ../
      dockerfile: Dockerfile.production
    image: mattrodriguesec/reservalab-backend:stage
    pull_policy: build
    