version: "3.9"

services:
#############
## backend ##
#############

  reservalab-backend-postgres:
    build:
      context: ./Database
      dockerfile: Dockerfile
    image: mattrodriguesec/reservalab-postgres:dev
    pull_policy: build

  reservalab-backend:
    build:
      context: ../
      dockerfile: Dockerfile
    image: mattrodriguesec/reservalab-backend:dev
    pull_policy: build
    
